2024-02-29 13:01:58,459 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 13:01:58,459 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Configure stats pid to 19656
2024-02-29 13:01:58,459 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\flora\.config\wandb\settings
2024-02-29 13:01:58,460 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\settings
2024-02-29 13:01:58,460 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'mlclass'}
2024-02-29 13:01:58,461 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 13:01:58,461 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 13:01:58,462 INFO    MainThread:19656 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130158-zsgaz9pj\logs\debug.log
2024-02-29 13:01:58,463 INFO    MainThread:19656 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130158-zsgaz9pj\logs\debug-internal.log
2024-02-29 13:01:58,463 INFO    MainThread:19656 [wandb_init.py:init():566] calling init triggers
2024-02-29 13:01:58,463 INFO    MainThread:19656 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-29 13:01:58,464 INFO    MainThread:19656 [wandb_init.py:init():616] starting backend
2024-02-29 13:01:58,465 INFO    MainThread:19656 [wandb_init.py:init():620] setting up manager
2024-02-29 13:01:58,482 INFO    MainThread:19656 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 13:01:58,484 INFO    MainThread:19656 [wandb_init.py:init():628] backend started and connected
2024-02-29 13:01:58,520 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 13:01:58,520 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 13:01:58,521 INFO    MainThread:19656 [wandb_init.py:init():720] updated telemetry
2024-02-29 13:01:59,967 INFO    MainThread:19656 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 13:02:00,933 ERROR   MainThread:19656 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-02-29 13:02:01,104 ERROR   MainThread:19656 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-02-29 13:02:46,017 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 13:02:46,018 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Configure stats pid to 19656
2024-02-29 13:02:46,018 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\flora\.config\wandb\settings
2024-02-29 13:02:46,018 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\settings
2024-02-29 13:02:46,018 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'mlclass'}
2024-02-29 13:02:46,019 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 13:02:46,019 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 13:02:46,020 INFO    MainThread:19656 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130245-ob8c2n5q\logs\debug.log
2024-02-29 13:02:46,021 INFO    MainThread:19656 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130245-ob8c2n5q\logs\debug-internal.log
2024-02-29 13:02:46,022 INFO    MainThread:19656 [wandb_init.py:init():566] calling init triggers
2024-02-29 13:02:46,022 INFO    MainThread:19656 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-29 13:02:46,023 INFO    MainThread:19656 [wandb_init.py:init():616] starting backend
2024-02-29 13:02:46,023 INFO    MainThread:19656 [wandb_init.py:init():620] setting up manager
2024-02-29 13:02:46,040 INFO    MainThread:19656 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 13:02:46,073 INFO    MainThread:19656 [wandb_init.py:init():628] backend started and connected
2024-02-29 13:02:46,107 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 13:02:46,109 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 13:02:46,109 INFO    MainThread:19656 [wandb_init.py:init():720] updated telemetry
2024-02-29 13:02:46,436 INFO    MainThread:19656 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 13:04:17,409 ERROR   MainThread:19656 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 13:04:17,581 ERROR   MainThread:19656 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 13:05:46,990 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 13:05:46,991 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Configure stats pid to 19656
2024-02-29 13:05:46,992 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\flora\.config\wandb\settings
2024-02-29 13:05:46,992 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\settings
2024-02-29 13:05:46,992 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'mlclass'}
2024-02-29 13:05:46,992 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 13:05:46,993 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 13:05:46,994 INFO    MainThread:19656 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130546-x69bn6mn\logs\debug.log
2024-02-29 13:05:46,995 INFO    MainThread:19656 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130546-x69bn6mn\logs\debug-internal.log
2024-02-29 13:05:46,996 INFO    MainThread:19656 [wandb_init.py:init():566] calling init triggers
2024-02-29 13:05:46,996 INFO    MainThread:19656 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-29 13:05:46,997 INFO    MainThread:19656 [wandb_init.py:init():616] starting backend
2024-02-29 13:05:46,997 INFO    MainThread:19656 [wandb_init.py:init():620] setting up manager
2024-02-29 13:05:47,001 INFO    MainThread:19656 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 13:05:47,004 INFO    MainThread:19656 [wandb_init.py:init():628] backend started and connected
2024-02-29 13:05:47,018 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 13:05:47,018 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 13:05:47,018 INFO    MainThread:19656 [wandb_init.py:init():720] updated telemetry
2024-02-29 13:05:47,387 INFO    MainThread:19656 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 13:07:00,546 WARNING MsgRouterThr:19656 [router.py:message_loop():77] message_loop has been closed
2024-02-29 13:07:18,307 ERROR   MainThread:19656 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 13:07:18,475 ERROR   MainThread:19656 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 13:07:34,235 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 13:07:34,237 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Configure stats pid to 19656
2024-02-29 13:07:34,237 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\flora\.config\wandb\settings
2024-02-29 13:07:34,239 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\settings
2024-02-29 13:07:34,239 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'mlclass'}
2024-02-29 13:07:34,239 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 13:07:34,239 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 13:07:34,240 INFO    MainThread:19656 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130734-jr93azyx\logs\debug.log
2024-02-29 13:07:34,241 INFO    MainThread:19656 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_130734-jr93azyx\logs\debug-internal.log
2024-02-29 13:07:34,241 INFO    MainThread:19656 [wandb_init.py:init():566] calling init triggers
2024-02-29 13:07:34,241 INFO    MainThread:19656 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-29 13:07:34,242 INFO    MainThread:19656 [wandb_init.py:init():616] starting backend
2024-02-29 13:07:34,242 INFO    MainThread:19656 [wandb_init.py:init():620] setting up manager
2024-02-29 13:07:34,250 INFO    MainThread:19656 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 13:07:34,253 INFO    MainThread:19656 [wandb_init.py:init():628] backend started and connected
2024-02-29 13:07:34,265 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 13:07:34,265 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 13:07:34,266 INFO    MainThread:19656 [wandb_init.py:init():720] updated telemetry
2024-02-29 13:07:34,601 INFO    MainThread:19656 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 13:07:50,786 WARNING MainThread:19656 [wandb_init.py:init():1198] interrupted
Traceback (most recent call last):
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 756, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-02-29 13:12:00,855 WARNING MsgRouterThr:19656 [router.py:message_loop():77] message_loop has been closed
2024-02-29 13:19:40,239 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-29 13:19:40,248 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Configure stats pid to 19656
2024-02-29 13:19:40,250 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\flora\.config\wandb\settings
2024-02-29 13:19:40,252 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\settings
2024-02-29 13:19:40,253 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'entity': 'mlclass'}
2024-02-29 13:19:40,254 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-29 13:19:40,255 INFO    MainThread:19656 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-29 13:19:40,256 INFO    MainThread:19656 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_131940-8ufak14p\logs\debug.log
2024-02-29 13:19:40,257 INFO    MainThread:19656 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\Flora\teste_Modelos\wandb\run-20240229_131940-8ufak14p\logs\debug-internal.log
2024-02-29 13:19:40,259 INFO    MainThread:19656 [wandb_init.py:init():566] calling init triggers
2024-02-29 13:19:40,260 INFO    MainThread:19656 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-29 13:19:40,260 INFO    MainThread:19656 [wandb_init.py:init():616] starting backend
2024-02-29 13:19:40,261 INFO    MainThread:19656 [wandb_init.py:init():620] setting up manager
2024-02-29 13:19:40,280 INFO    MainThread:19656 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-29 13:19:40,291 INFO    MainThread:19656 [wandb_init.py:init():628] backend started and connected
2024-02-29 13:19:40,430 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-29 13:19:40,430 INFO    MainThread:19656 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-29 13:19:40,431 INFO    MainThread:19656 [wandb_init.py:init():720] updated telemetry
2024-02-29 13:19:40,756 INFO    MainThread:19656 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-29 13:21:11,708 ERROR   MainThread:19656 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 13:21:12,551 ERROR   MainThread:19656 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\flora\OneDrive\Documentos\MESTRADO_UFSC\rotinas\python\MESTRA\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-02-29 14:06:41,853 WARNING MsgRouterThr:19656 [router.py:message_loop():77] message_loop has been closed
2024-02-29 14:53:22,072 WARNING MsgRouterThr:19656 [router.py:message_loop():77] message_loop has been closed
2024-02-29 15:20:37,035 WARNING MsgRouterThr:19656 [router.py:message_loop():77] message_loop has been closed
